#!/bin/sh
set -e pipefail 

# Apply formatting
cargo fmt --all || {
    echo "❌ Cannot fmt code (run 'cargo fmt --all')"
    exit 1
}

# Dependency sorting in Cargo.toml
cargo sort --workspace || {
    echo "❌ Cannot sort dependencies (run 'cargo sort --workspace')"
    exit 1
}
