[package]
name = "examples"
publish = false
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# TODO(template) update the crate name
template_crate = { path = "../template_crate" }
