name: Semver checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # cargo-semver-checks needs the full git history to compare versions
        fetch-depth: 0
    
    - name: Check semver compatibility
      uses: obi1kenobi/cargo-semver-checks-action@v2
      with:
        # Check all packages in the workspace
        package: --workspace
        # Only run on packages that have been published before
        # This prevents errors on new packages that haven't been published yet
        baseline-version: auto