name: UB (undefined behavior) detection

on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  ub-detection:
    if: github.event.pull_request.draft == false
    name: Check for undefined behaviour (UB)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: |
          rustup +nightly component add miri
          cargo +nightly miri setup
          PROPTEST_DISABLE_FAILURE_PERSISTENCE=true \
            MIRIFLAGS="-Zmiri-env-forward=PROPTEST_DISABLE_FAILURE_PERSISTENCE -Zmiri-strict-provenance" \
            cargo +nightly miri test --lib
